---

- name: Update apt packages
  apt:
    update_cache: yes

- name: Docker is present
  apt:
    name: docker.io
    state: present

- name: Python3-docker is present
  apt:
    name: python3-docker
    state: present

- name: Ensure docker deamon is running
  service:
    name: docker
    state: started

- name: Create docker network
  docker_network:
    name: "{{ network_name }}"